{
 "title": "System Data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "exporter_memory_total_bytes{job=\"go_exporter\"}",
     "legendFormat": "Total Memory"
    },
    { "expr": "exporter_memory_used_bytes", "legendFormat": "Used Memory" }
   ]
  },
  {
   "title": "Mem Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(exporter_memory_used_bytes / exporter_memory_total_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk info",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(exporter_disk_used_bytes{mountpoint=\"/\"} / exporter_disk_total_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "exporter_cpu_usage_percent", "legendFormat": "CPU Percent" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "exporter_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}