version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exporter
    ports:
      - "8080:8080"
    environment:
      - EXPORTER_HOST=0.0.0.0
      - EXPORTER_PORT=8080
      - EXPORTER_METRICS_INTERVAL=10
